import React, { Component } from "react";
import { Container, Form, Modal, Carousel } from "react-bootstrap";
import fullLogo from "./assets/fullLogo.png";
import dataService from "./services/DataService";
import { withRouter } from "react-router-dom";
import Checkout from "./Checkout";
import SuccessfulPurchase from "./SuccessfulPurchase";
import PortfolioToken from "./PortfolioToken";
import RewardToken from "./RewardToken";
import chainService from "./services/ChainService";
import NumberService from "./services/NumberService";
import LoadingOverlay from "react-loading-overlay";

import tutorial1 from "./assets/tutorial1.png";
import tutorial2 from "./assets/tutorial2.png";
import tutorial3 from "./assets/tutorial3.png";

class Tutorial extends Component {
	constructor(props) {
		super(props);
		this.onSlid = this.onSlid.bind(this);
		this.onEnd = this.onEnd.bind(this);

		this.state = {
			pageIndex: 0,
		};
	}

	componentDidMount() {}

	onSlid(eventKey) {
		this.setState({ pageIndex: eventKey });
	}

	onEnd() {
		window.location.href = "/home";
	}

	render() {
		return (
			<Container>
				<table class="welcomeTitle">
					<tr>
						<td>
							<img src={fullLogo} alt="" class="smallLogo" />
						</td>
						<td class="alignRight">
							{/* <button class="skipButton">Skip</button> */}

							<button onClick={this.onEnd} class="skipStyle">
								Skip
							</button>
						</td>
					</tr>
				</table>
				<Carousel
					interval={null}
					controls={true}
					wrap={false}
					touch={true}
					onSlid={this.onSlid}
				>
					<Carousel.Item>
						<table class="tutorialTable">
							<tr>
								<td>
									<img src={tutorial1} />
								</td>
							</tr>
							<tr>
								<td>
									<div class="tutorialMain">Access real world investments</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="tutorialBody">
										AlloyX protocol creates pooled investment tokens backed by
										income generating assets
									</div>
								</td>
							</tr>
						</table>
					</Carousel.Item>
					<Carousel.Item>
						<table class="tutorialTable">
							<tr>
								<td>
									<img src={tutorial2} />
								</td>
							</tr>
							<tr>
								<td>
									<div class="tutorialMain">Earn income & reinvest</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="tutorialBody">
										AlloyX uses the income generated by the assets to provide
										regular payments to token holders and reinvests some of the
										earning to grow the net asset value per token
									</div>
								</td>
							</tr>
						</table>
					</Carousel.Item>
					<Carousel.Item>
						<table class="tutorialTable">
							<tr>
								<td>
									<img src={tutorial3} />
								</td>
							</tr>
							<tr>
								<td>
									<div class="tutorialMain">Earn ALYX rewards</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="tutorialBody">
										Use the liquidity pools to trade and hold pooled investment
										tokens to also earn rewards in ALYX, AlloyX protocol utility
										tokens, and capture additional upside
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<button onClick={this.onEnd} class="startStyle">
										Start
									</button>
								</td>
							</tr>
						</table>
					</Carousel.Item>
				</Carousel>
			</Container>
		);
	}
}

export default withRouter(Tutorial);
